### ISSUE TITLE
Please provide example code and/or docs

### ISSUE THREAD

**Issue by NeutronStein** [euroelessar/jreen#33]
Please provide example code and/or docs. Thanks.

**Comment by nico-izo** [comment]
You can take a look at simple jreen jabber bot here: https://code.launchpad.net/~torkvemada/+junk/aaron

There are no much features, so if you want examples of advanced use of jreen, I know only qutIM (jabber protocol) and tomahawk-player.

**Comment by NeutronStein** [comment]
Thanks @nico-izo
